apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: painelplan-prod
resources:
- ../../base
images:
- name: dti-registro.unilab.edu.br/unilab/painelplanejamento:main
  newName: dti-registro.unilab.edu.br/unilab/painelplanunilab
  newTag: latest
patches:
- path: configmap.yaml
- path: deployment.yaml
- path: ingress.yaml
