apiVersion: apps/v1
kind: Deployment
metadata:
  name: painelplan-unilab
  namespace: painelplan
spec:
  selector:
    matchLabels:
      app: painelplan-unilab
  template:
    metadata:
      labels:
        app: painelplan-unilab
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/painelplanejamento/config'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/data/painelplanejamento/config" -}}
            {{ .Data.data.ssh_dev }}
          {{ .Data.data.ssh_ops }}
          {{- end }}
        vault.hashicorp.com/role: "painelplanejamento-stag-role"
        vault.hashicorp.com/auth-path: auth/kubernetes/c3
    spec:
      serviceAccountName: "sa-painelplan"
      containers:
      - name: painelplan-unilab
        command:
        - /bin/bash
        - -cp
        - |
          cat /vault/secrets/config >> /home/admin/.ssh/authorized_keys
          service ssh restart
          nginx -g 'daemon off;'
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 990m
            memory: 1024Mi
        ports:
        - containerPort: 22
          name: ssh

