apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mapaderisco-stag
resources:
- ../../base
images:
- name: dti-registro.unilab.edu.br/unilab/mapaderisco:main
  newName: dti-registro.unilab.edu.br/unilab/mapaderisco
  newTag: latest
patches:
- path: configmap.yaml
- path: deployment.yaml
- path: service.yaml
- path: ingress.yaml
