apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- namespace.yaml
- secret-regcred.yaml
- sa.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
